backend:
    -   changed-files:
            -   any-glob-to-any-file:
                    - '**/*.kt'
                    - 'src/**'
                    - 'build.gradle.kts'
                    - 'gradle/**'

frontend:
    -   changed-files:
            -   any-glob-to-any-file:
                    - 'themes/olx/**'

ops:
    -   changed-files:
            -   any-glob-to-any-file:
                    - '.github/**'
                    - 'lefthook.yml'
